server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    neo4j:
      username: neo4j
      password: 990424
      uri: http://localhost:7474
#      uri: http://172.20.10.2:7474
  main:
    # 想知道这个配置干嘛的，删了之后看报错
    allow-bean-definition-overriding: true